import type { TranscribeResponse, BenchmarkResponse } from "@/types/api";

export const MOCK_TRANSCRIBE: TranscribeResponse = {
  raw_transcript: [
    { word: "Doctor:", start_ms: 0, end_ms: 200, speaker: "Doctor", confidence: "HIGH" },
    { word: "Let's", start_ms: 210, end_ms: 350, speaker: "Doctor", confidence: "HIGH" },
    { word: "review", start_ms: 360, end_ms: 520, speaker: "Doctor", confidence: "HIGH" },
    { word: "your", start_ms: 530, end_ms: 620, speaker: "Doctor", confidence: "HIGH" },
    { word: "medications.", start_ms: 630, end_ms: 900, speaker: "Doctor", confidence: "HIGH" },
    { word: "You're", start_ms: 910, end_ms: 1050, speaker: "Doctor", confidence: "HIGH" },
    { word: "currently", start_ms: 1060, end_ms: 1300, speaker: "Doctor", confidence: "HIGH" },
    { word: "on", start_ms: 1310, end_ms: 1380, speaker: "Doctor", confidence: "HIGH" },
    { word: "metoformin", start_ms: 1390, end_ms: 1700, speaker: "Doctor", confidence: "LOW", uncertainty_signals: ["phonetic_distance: 1", "keyterm_mismatch", "timing_irregularity"] },
    { word: "500", start_ms: 1710, end_ms: 1850, speaker: "Doctor", confidence: "MEDIUM", uncertainty_signals: ["timing_irregularity"] },
    { word: "milligrams", start_ms: 1860, end_ms: 2200, speaker: "Doctor", confidence: "HIGH" },
    { word: "twice", start_ms: 2210, end_ms: 2400, speaker: "Doctor", confidence: "HIGH" },
    { word: "daily,", start_ms: 2410, end_ms: 2600, speaker: "Doctor", confidence: "HIGH" },
    { word: "and", start_ms: 2610, end_ms: 2700, speaker: "Doctor", confidence: "HIGH" },
    { word: "lisinipril", start_ms: 2710, end_ms: 3100, speaker: "Doctor", confidence: "LOW", uncertainty_signals: ["phonetic_distance: 1", "keyterm_mismatch"] },
    { word: "10mg.", start_ms: 3110, end_ms: 3350, speaker: "Doctor", confidence: "HIGH" },
    { word: "Patient:", start_ms: 3800, end_ms: 4000, speaker: "Patient", confidence: "HIGH" },
    { word: "Yes,", start_ms: 4010, end_ms: 4150, speaker: "Patient", confidence: "HIGH" },
    { word: "and", start_ms: 4160, end_ms: 4250, speaker: "Patient", confidence: "HIGH" },
    { word: "I've", start_ms: 4260, end_ms: 4400, speaker: "Patient", confidence: "HIGH" },
    { word: "been", start_ms: 4410, end_ms: 4530, speaker: "Patient", confidence: "HIGH" },
    { word: "having", start_ms: 4540, end_ms: 4700, speaker: "Patient", confidence: "HIGH" },
    { word: "headaches", start_ms: 4710, end_ms: 5050, speaker: "Patient", confidence: "HIGH" },
    { word: "and", start_ms: 5060, end_ms: 5150, speaker: "Patient", confidence: "HIGH" },
    { word: "dizziness", start_ms: 5160, end_ms: 5500, speaker: "Patient", confidence: "MEDIUM", uncertainty_signals: ["timing_irregularity"] },
    { word: "since", start_ms: 5510, end_ms: 5650, speaker: "Patient", confidence: "HIGH" },
    { word: "starting", start_ms: 5660, end_ms: 5900, speaker: "Patient", confidence: "HIGH" },
    { word: "the", start_ms: 5910, end_ms: 5980, speaker: "Patient", confidence: "HIGH" },
    { word: "atorvostatin.", start_ms: 5990, end_ms: 6400, speaker: "Patient", confidence: "LOW", uncertainty_signals: ["phonetic_distance: 2", "keyterm_mismatch", "correction_likelihood: high"] },
  ],
  corrected_transcript: [
    { word: "Doctor:", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "Let's", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "review", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "your", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "medications.", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "You're", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "currently", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "on", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "metformin", changed: true, tavily_verified: true, unverified: false, speaker: "Doctor" },
    { word: "500", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "milligrams", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "twice", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "daily,", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "and", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "lisinopril", changed: true, tavily_verified: true, unverified: false, speaker: "Doctor" },
    { word: "10mg.", changed: false, tavily_verified: false, unverified: false, speaker: "Doctor" },
    { word: "Patient:", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "Yes,", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "and", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "I've", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "been", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "having", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "headaches", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "and", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "dizziness", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "since", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "starting", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "the", changed: false, tavily_verified: false, unverified: false, speaker: "Patient" },
    { word: "atorvastatin.", changed: true, tavily_verified: true, unverified: false, speaker: "Patient" },
  ],
  clinical_summary: {
    medications: [
      { name: "Metformin", dosage: "500mg", frequency: "Twice daily", route: "Oral", tavily_verified: true },
      { name: "Lisinopril", dosage: "10mg", frequency: "Once daily", route: "Oral", tavily_verified: true },
      { name: "Atorvastatin", dosage: "Unknown", frequency: "Unknown", route: "Oral", tavily_verified: true },
    ],
    symptoms: ["Headaches", "Dizziness"],
    allergies: [],
    follow_up_actions: [
      "Review atorvastatin dosage and side effects",
      "Monitor blood pressure at next visit",
      "Schedule follow-up in 2 weeks",
    ],
    appointment_needed: true,
  },
  pipeline_latency_ms: { preprocessing: 85, scribe: 420, uncertainty: 45, tavily: 380, claude: 1200, total: 2130 },
};

export const MOCK_BENCHMARK: BenchmarkResponse = {
  ablation: [
    { stage: "Raw Scribe v2 (no preprocessing, no keyterms)", wer: 21.4, delta: 0, description: "Baseline — how bad the problem is on raw telephony audio" },
    { stage: "+ Audio Preprocessing (ffmpeg chain)", wer: 18.2, delta: 3.2, description: "Preprocessing alone reduces WER — ffmpeg earns its place" },
    { stage: "+ Keyterm Prompting (initial 50-term list)", wer: 16.1, delta: 2.1, description: "Keyterms reduce medical terminology errors before any correction" },
    { stage: "+ Dynamic Vocabulary (learning loop)", wer: 15.0, delta: 1.1, description: "Adaptive vocabulary shows measurable improvement over static list" },
    { stage: "+ Tavily Verification + Safe Correction", wer: 13.5, delta: 1.5, description: "Final corrected WER — only verified terms corrected, zero hallucinations" },
  ],
  metrics: {
    verification_rate: 100,
    unsafe_guess_rate: 0,
    uncertainty_coverage: 94,
    phonetic_hit_rate: 87,
  },
  results: [
    { clip_id: "clip_01", category: "Medication Refill", difficulty: "Standard", raw_wer: 18.2, corrected_wer: 11.4, improvement_pct: 37.4 },
    { clip_id: "clip_02", category: "Medication Refill", difficulty: "Standard", raw_wer: 15.8, corrected_wer: 10.1, improvement_pct: 36.1 },
    { clip_id: "clip_03", category: "Post-op Follow-up", difficulty: "Standard", raw_wer: 22.1, corrected_wer: 14.3, improvement_pct: 35.3 },
    { clip_id: "clip_04", category: "Post-op Follow-up", difficulty: "Standard", raw_wer: 24.5, corrected_wer: 15.8, improvement_pct: 35.5 },
    { clip_id: "clip_05", category: "New Symptom Check", difficulty: "Standard", raw_wer: 19.3, corrected_wer: 12.1, improvement_pct: 37.3 },
    { clip_id: "clip_06", category: "New Symptom Check", difficulty: "Standard", raw_wer: 17.6, corrected_wer: 11.2, improvement_pct: 36.4 },
    { clip_id: "clip_07", category: "Allergy Review", difficulty: "Standard", raw_wer: 20.4, corrected_wer: 13.0, improvement_pct: 36.3 },
    { clip_id: "clip_08", category: "Allergy Review", difficulty: "Standard", raw_wer: 16.9, corrected_wer: 10.8, improvement_pct: 36.1 },
    { clip_id: "clip_09", category: "Dosage Query", difficulty: "Standard", raw_wer: 21.0, corrected_wer: 13.5, improvement_pct: 35.7 },
    { clip_id: "clip_10", category: "Dosage Query", difficulty: "Standard", raw_wer: 19.7, corrected_wer: 12.6, improvement_pct: 36.0 },
    { clip_id: "clip_11", category: "Medication Refill", difficulty: "Adversarial", raw_wer: 28.5, corrected_wer: 17.1, improvement_pct: 40.0 },
    { clip_id: "clip_12", category: "Post-op Follow-up", difficulty: "Adversarial", raw_wer: 31.2, corrected_wer: 19.5, improvement_pct: 37.5 },
    { clip_id: "clip_13", category: "New Symptom Check", difficulty: "Adversarial", raw_wer: 26.8, corrected_wer: 16.8, improvement_pct: 37.3 },
    { clip_id: "clip_14", category: "Allergy Review", difficulty: "Adversarial", raw_wer: 29.4, corrected_wer: 18.2, improvement_pct: 38.1 },
    { clip_id: "clip_15", category: "Dosage Query", difficulty: "Adversarial", raw_wer: 25.1, corrected_wer: 15.9, improvement_pct: 36.7 },
    { clip_id: "clip_16", category: "Heavy Accent", difficulty: "Adversarial", raw_wer: 34.6, corrected_wer: 21.8, improvement_pct: 37.0 },
    { clip_id: "clip_17", category: "Elderly Speaker", difficulty: "Adversarial", raw_wer: 27.3, corrected_wer: 17.4, improvement_pct: 36.3 },
    { clip_id: "clip_18", category: "Rapid Med List", difficulty: "Adversarial", raw_wer: 30.8, corrected_wer: 19.2, improvement_pct: 37.7 },
    { clip_id: "clip_19", category: "Soft Voice + Noise", difficulty: "Adversarial", raw_wer: 33.1, corrected_wer: 21.0, improvement_pct: 36.6 },
    { clip_id: "clip_20", category: "Background Noise", difficulty: "Adversarial", raw_wer: 35.9, corrected_wer: 22.7, improvement_pct: 36.8 },
  ],
  aggregate: {
    avg_raw_wer: 24.9,
    avg_corrected_wer: 15.7,
    avg_improvement_pct: 37.0,
    keyterm_impact_pct: 12.3,
  },
  comparison: {
    base_model: {
      id: "openai/whisper-small",
      label: "Base Whisper Small",
      clip_count: 20,
      avg_wer: 29.4,
      avg_cer: 15.2,
      avg_digit_accuracy: 61.0,
      avg_medical_keyword_accuracy: 58.0,
    },
    fine_tuned_model: {
      id: "full_ft",
      label: "Fine-Tuned Telephony",
      clip_count: 20,
      avg_wer: 20.8,
      avg_cer: 11.1,
      avg_digit_accuracy: 80.0,
      avg_medical_keyword_accuracy: 76.0,
    },
    delta: {
      wer_reduction: 8.6,
      cer_reduction: 4.1,
      digit_accuracy_gain: 19.0,
      medical_keyword_accuracy_gain: 18.0,
    },
    per_clip: [],
  },
  model_benchmarks: [
    {
      id: "base_whisper_small",
      label: "Base Whisper Small",
      clip_count: 20,
      avg_wer: 29.4,
      avg_cer: 15.2,
      avg_digit_accuracy: 61.0,
      avg_medical_keyword_accuracy: 58.0,
    },
    {
      id: "scribe_v2",
      label: "ScribeV2",
      clip_count: 20,
      avg_wer: 24.9,
      avg_cer: 13.4,
      avg_digit_accuracy: 68.0,
      avg_medical_keyword_accuracy: 64.0,
    },
    {
      id: "fine_tuned_telephony",
      label: "Whisper Fine-Tuned",
      clip_count: 20,
      avg_wer: 20.8,
      avg_cer: 11.1,
      avg_digit_accuracy: 80.0,
      avg_medical_keyword_accuracy: 76.0,
    },
    {
      id: "lora",
      label: "Whisper LoRA",
      clip_count: 20,
      avg_wer: 19.6,
      avg_cer: 10.5,
      avg_digit_accuracy: 82.0,
      avg_medical_keyword_accuracy: 79.0,
    },
    {
      id: "emergency_lora",
      label: "Emergency LoRA",
      clip_count: 20,
      avg_wer: 22.4,
      avg_cer: 12.3,
      avg_digit_accuracy: 78.0,
      avg_medical_keyword_accuracy: 72.0,
    },
  ],
};

export const DEMO_CLIPS = [
  { id: "clip_01", name: "Medication Refill — American Male", category: "Medication Refill", difficulty: "Standard" as const },
  { id: "clip_02", name: "Medication Refill — British Female", category: "Medication Refill", difficulty: "Standard" as const },
  { id: "clip_03", name: "Post-op Follow-up — South Asian Male", category: "Post-op Follow-up", difficulty: "Standard" as const },
  { id: "clip_04", name: "Post-op Follow-up — East Asian Female", category: "Post-op Follow-up", difficulty: "Standard" as const },
  { id: "clip_05", name: "Symptom Check — Hispanic Female", category: "New Symptom Check", difficulty: "Standard" as const },
  { id: "clip_06", name: "Symptom Check — Elderly Male", category: "New Symptom Check", difficulty: "Standard" as const },
  { id: "clip_07", name: "Allergy Review — Eastern European Male", category: "Allergy Review", difficulty: "Standard" as const },
  { id: "clip_08", name: "Allergy Review — American Female", category: "Allergy Review", difficulty: "Standard" as const },
  { id: "clip_09", name: "Dosage Query — Fast Doctor", category: "Dosage Query", difficulty: "Standard" as const },
  { id: "clip_10", name: "Dosage Query — Patient Voice", category: "Dosage Query", difficulty: "Standard" as const },
  { id: "clip_11", name: "ADVERSARIAL: Heavy Accent + Fast", category: "Heavy Accent", difficulty: "Adversarial" as const },
  { id: "clip_12", name: "ADVERSARIAL: Elderly + Speakerphone", category: "Elderly Speaker", difficulty: "Adversarial" as const },
  { id: "clip_13", name: "ADVERSARIAL: Rapid Med List", category: "Rapid Med List", difficulty: "Adversarial" as const },
  { id: "clip_14", name: "ADVERSARIAL: Soft Voice + Noise", category: "Soft Voice + Noise", difficulty: "Adversarial" as const },
  { id: "clip_15", name: "ADVERSARIAL: Pure Background Noise", category: "Background Noise", difficulty: "Adversarial" as const },
];
